#!/usr/bin/env bash

#Configure your domain zone so that the subdomain 
#www points to your load-balancer IP (lb-01). Let’s also add other subdomains to 
#make our life easier, and write a Bash script that will display information about subdomains.

# coloring
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'
YELLOW='\033[1;33m'
# variables and paramaters 
subdomains=("www" "lb-01" "web-01" "web-02")
domain="$1"
sub="$2"

# logic using dig and awk tool

dig_cmd () {
	# func variables
	sub="$2"
	INFO="$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"
	IP=$(echo "$INFO" | awk '{print $5}')
	RECORD=$(echo "$INFO" | awk '{print $4}')

	echo -e "${YELLOW}The subdomain ${RED}$sub${YELLOW} is a ${GREEN}$RECORD${YELLOW} record and points to ${GREEN}$IP${NC}"
}

if [ $# -eq 1 ]; then
	for subs in "${subdomains[@]}"; do
		dig_cmd "$domain" "$subs"
	done
elif [ $# -eq 2 ]; then
	dig_cmd "$domain" "$sub"
fi