#!/usr/bin/env bash
# install the nigx into web server
# coloring
# RED='\e[31m'
YELLOW='\e[33m'
GREEN='\e[32m'
NC='\e[0m'

#updating and installing the nigx
echo -e "${YELLOW}[!] updating your system and installing the nginx${NC}"
sudo apt-get update -y
sudo apt-get install nginx -y
echo -e "${GREEN}[+] nginx installed${NC}"

# setting up the nigx
echo -e "$YELLOW [!] starting the nigx"
sudo service nginx start

# allowing the nigx on the firewall(activate it)
echo -e "$YELLOW [!] allowing the nigx on the firewall $NC"
sudo ufw allow 'Nginx HTTP'
echo -e "$YELLOW [!] done allowing the nigx on the firewall${NC}"

# write hello world
echo -e "$YELLOW [!] write hello world"
echo "Hello World!" | sudo tee /var/www/html/index.html
# redirecting to youtube
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# page not found
# Set up a 404 page
sudo sed -i '/^}$/i \ \n\tlocation @404 {return 404 "Ceci n'\''est pas une page\\n";}' /etc/nginx/sites-available/default
sudo sed -i 's/=404/@404/g' /etc/nginx/sites-available/default

sudo service nginx reload
echo -e "$YELLOW [!] done${NC}"
