#!/usr/bin/env bash
# configure the server to start lisrenning on the port 80

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid 
