#!/usr/bin/env bash
#Write a manage_my_process Bash script that:
    #Indefinitely writes I am alive! to the file /tmp/my_process
    #In between every I am alive! message, the program should pause for 2 seconds
#Write Bash (init) script 101-manage_my_process that manages manage_my_process. (both files need to be pushed to git)
command="$1"
file="/var/run/my_process.pid"
if [ -z "$command" ]; then
    echo "Usage: manage_my_process {start|stop|restart}"
    exit
fi
case $command in
    start)
        ./manage_my_process &
        echo "$!" > $file
        echo "manage_my_process started"
        ;;
    stop)
        if [ -e $file ]; then
          pkill -f './manage_my_process' &&
          rm $file
          echo "manage_my_process stopped"
        fi
        ;;
    restart)
        "$0" stop >& /dev/null
        "$0" start >& /dev/null
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
