#!/usr/bin/env bash
#Write a manage_my_process Bash script that:
    #Indefinitely writes I am alive! to the file /tmp/my_process
    #In between every I am alive! message, the program should pause for 2 seconds
#Write Bash (init) script 101-manage_my_process that manages manage_my_process. (both files need to be pushed to git)
command="$1"
file="/var/run/my_process.pid"
if [ -z "$command" ]; then
    echo "Usage: manage_my_process {start|stop|restart}"
    exit
fi
# dashbord that manage the PID porcess using condition
if [ "$command" == "start" ]; then
    ./manage_my_process &
    echo "$!" > $file
    echo "manage_my_process started"
elif [ "$command" == "stop" ]; then
     [ -e $file ] &&
    pkill -f './manage_my_process' &&
    rm $file
    echo "manage_my_process stopped"
elif [ "$command" == "restart" ]; then
    "$0" stop >& /dev/null
    "$0" start >& /dev/null
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
