#!/usr/bin/env bash
# script that print Best school using while loop
# declare variable called i for looping

i=1
while [ $i -le 10 ]
do
  # print Best School
  printf "Best School\n"
  # increment i
  ((i++))
done
