#!/usr/bin/env bash
# displays bad luck, good luck, best school
# declare a variable with value 1
i=1

while [ $i -le 10 ]
do
  # at the line 4th print bad luck
  if [ $i -eq 4 ]
  then 
    printf "bad luck\n"
  elif [ $i -eq 8 ] # at the line 8th print good luck
  then
    printf "good luck\n"
  else 
    # print best school at the rest
    printf "Best School\n"
  fi
  # increment the variable
  ((i++))
done

